name: example
description: A new Flutter project.
version: 2.0.0+2

environment:
  sdk: '>=3.0.3 <4.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.8.0
  flame_texturepacker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/